# Generated by Django 5.2.3 on 2025-06-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_events', '0001_initial'),
        ('invitations', '0003_alter_invitation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='election_event',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='election_events.electionevent'),
            preserve_default=False,
        ),
    ]
