# Generated by Django 5.2.3 on 2025-06-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_events', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_event',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='election_events.electionevent'),
            preserve_default=False,
        ),
    ]
