# Generated by Django 5.2.3 on 2025-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_created_at_alter_voterprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
