# Generated by Django 5.2.3 on 2025-06-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_events', '0001_initial'),
        ('users', '0005_alter_user_created_at_alter_voterprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterprofile',
            name='election_event',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='voter_profiles', to='election_events.electionevent'),
            preserve_default=False,
        ),
    ]
